-- UMRT Shop -- initial product seed from real, cited public pricing.
-- Every row: retail_price + price_source are real and verifiable.
-- cost/margin are NULL -- no wholesale cost has been confirmed yet.
-- Artek rows: active=1 candidate (Matt has a real account with Artek).
-- Dometic rows: active=0 (unpublished) -- fulfillment path not yet confirmed;
-- Dometic itself doesn't drop-ship direct, and no specific reseller account
-- has been confirmed among the cited sources (Defender / Upfitters Wholesale
-- / RV Parts Giant). Flip active=1 once Matt confirms which one (if any) he
-- actually has an account/relationship with.

INSERT OR IGNORE INTO products (id, sku, manufacturer, model, title, description, category, product_type, retail_price, price_source, supplier_id, stock_status, installation_required, active) VALUES
  ('artek-alpha2pro-200', NULL, 'Artek', 'ALPHA 2 PRO 12V 200Ah', 'ALPHA 2 PRO 12V 200Ah LiFePO4 Battery', '12V 200Ah lithium (LiFePO4) battery, 7,000+ lifetime cycles.', 'rv-batteries', 'individual', 1199.99, 'artek.energy public price, cited by Matt 2026-09-12', 'artek', 'unverified', 1, 1),
  ('artek-epoch-eco-12v', NULL, 'Epoch', 'Eco Series 12V', 'Epoch 12V Eco Series LiFePO4 Battery', 'Entry-level 12V lithium battery line, price varies by capacity.', 'rv-batteries', 'individual', 325.00, 'artek.energy public price (starting price), cited by Matt 2026-09-12', 'artek', 'unverified', 1, 1),
  ('artek-epoch-elite-v2', NULL, 'Epoch', 'Elite V2 Series', 'Epoch Elite V2 Series LiFePO4 Battery', 'Mid/high-capacity lithium battery line, price varies by capacity.', 'rv-batteries', 'individual', 1999.00, 'artek.energy public price (starting price), cited by Matt 2026-09-12', 'artek', 'unverified', 1, 1),
  ('artek-epoch-v2t', NULL, 'Epoch', 'V2-T Series', 'Epoch V2-T Series LiFePO4 Battery', 'Top-tier lithium battery line, price varies by capacity.', 'rv-batteries', 'individual', 2399.00, 'artek.energy public price (starting price), cited by Matt 2026-09-12', 'artek', 'unverified', 1, 1),
  ('artek-flex-210w', NULL, 'Artek', '210W Flexible', 'Artek 210W Flexible Solar Panel', 'Flexible rooftop solar panel, 210W.', 'rv-solar', 'individual', 900.00, 'artek.energy public price, cited by Matt 2026-09-12', 'artek', 'unverified', 1, 1),
  ('artek-flex-170w', NULL, 'Artek', '170W Slim Flexible', 'Artek 170W Slim Flexible Solar Panel', 'Slim flexible rooftop solar panel, 170W.', 'rv-solar', 'individual', 728.00, 'artek.energy public price, cited by Matt 2026-09-12', 'artek', 'unverified', 1, 1),
  ('artek-ja440w-kit', NULL, 'Artek', '3-Panel JA 440W Kit', '3-Panel Solar Kit for Premium Systems (JA 440W)', 'Three-panel JA solar kit, 440W combined, for premium off-grid systems.', 'rv-solar', 'kit', 1287.00, 'artek.energy public price, cited by Matt 2026-09-12', 'artek', 'unverified', 1, 1),
  ('richsolar-mega-100w', NULL, 'Rich Solar', 'MEGA 12V 100W Mono', 'Rich Solar MEGA 12V 100W Monocrystalline Panel', 'Rigid monocrystalline solar panel, 100W.', 'rv-solar', 'individual', 119.99, 'artek.energy public price, cited by Matt 2026-09-12', 'artek', 'unverified', 0, 1),
  ('richsolar-mega-150w', NULL, 'Rich Solar', 'MEGA 12V 150W Mono', 'Rich Solar MEGA 12V 150W Monocrystalline Panel', 'Rigid monocrystalline solar panel, 150W.', 'rv-solar', 'individual', 169.99, 'artek.energy public price, cited by Matt 2026-09-12', 'artek', 'unverified', 0, 1),
  ('victron-smartsolar-mppt', NULL, 'Victron Energy', 'SmartSolar MPPT', 'Victron SmartSolar MPPT Charge Controller', 'Solar charge controller, price varies by model/amperage -- starting price shown.', 'rv-power-protection', 'individual', 65.45, 'artek.energy public price (starting price), cited by Matt 2026-09-12', 'artek', 'unverified', 1, 1),
  ('victron-lynx-distributor', NULL, 'Victron Energy', 'Lynx Distributor', 'Victron Energy Lynx Distributor', 'Busbar distribution and fusing module for Victron DC systems.', 'rv-power-protection', 'individual', 220.00, 'artek.energy public price (GBP 175 converted), cited by Matt 2026-09-12', 'artek', 'unverified', 1, 1),
  ('victron-gxtouch50', NULL, 'Victron Energy', 'GX Touch 50', 'Victron GX Touch 50 System Monitor', 'Touchscreen system monitor for Victron GX devices -- starting price shown.', 'rv-power-protection', 'individual', 220.15, 'artek.energy public price (starting price), cited by Matt 2026-09-12', 'artek', 'unverified', 1, 1),
  ('maxxair-7500k', NULL, 'Maxxair', 'Fan 7500K', 'Maxxair Fan 7500K', 'Powered roof ventilation fan.', 'rv-roof-ventilation', 'individual', 340.00, 'artek.energy public price, cited by Matt 2026-09-12', 'artek', 'unverified', 1, 1);

-- Dometic reference rows -- unpublished until a real fulfillment account is confirmed.
INSERT OR IGNORE INTO products (id, sku, manufacturer, model, title, description, category, product_type, retail_price, price_source, supplier_id, stock_status, installation_required, active) VALUES
  ('dometic-rtx2000', NULL, 'Dometic', 'RTX 2000', 'Dometic RTX 2000 Head Unit (12V DC)', '12V DC-powered rooftop A/C head unit.', 'rv-climate', 'individual', 2399.99, 'street price citing defender.com/upfitterswholesale.com/rvpartsgiant.com, cited by Matt 2026-09-12', NULL, 'unverified', 1, 0),
  ('dometic-freshjet-48v', NULL, 'Dometic', 'FreshJet 48V', '48V FreshJet DC-Powered Rooftop A/C + Heat Pump', 'DC-powered rooftop A/C with heat pump.', 'rv-climate', 'individual', 3199.00, 'street price citing defender.com/upfitterswholesale.com/rvpartsgiant.com, cited by Matt 2026-09-12', NULL, 'unverified', 1, 0),
  ('dometic-rtx-installkit', NULL, 'Dometic', 'RTX Premium Install Kit', 'Dometic RTX Premium Install Kit', 'Premium installation accessory kit for RTX head units.', 'rv-climate', 'individual', 399.99, 'street price citing defender.com/upfitterswholesale.com/rvpartsgiant.com, cited by Matt 2026-09-12', NULL, 'unverified', 1, 0),
  ('dometic-rtx-wiringkit', NULL, 'Dometic', 'RTX 4AWG Wiring Kit 26ft', 'Dometic RTX 4AWG Wiring Kit (26 ft)', 'Wiring kit for RTX head unit installs.', 'rv-climate', 'individual', 399.99, 'street price citing defender.com/upfitterswholesale.com/rvpartsgiant.com, cited by Matt 2026-09-12', NULL, 'unverified', 1, 0),
  ('dometic-penguin2', NULL, 'Dometic', 'Penguin II (13.5k/15k BTU)', 'Dometic Penguin II Rooftop A/C', 'Standard rooftop A/C, 13.5k or 15k BTU -- price range shown.', 'rv-climate', 'individual', 1075.00, 'street price range $900-$1250, midpoint shown, citing upfitterswholesale.com/rvfridgeguys.com, cited by Matt 2026-09-12', NULL, 'unverified', 1, 0),
  ('dometic-smartstart', NULL, 'Dometic', 'SmartStart', 'Dometic SmartStart Soft Starter', 'Soft-start accessory to reduce A/C generator/inverter startup load.', 'rv-climate', 'individual', 566.22, 'street price range $549-$583.44, midpoint shown, cited by Matt 2026-09-12', NULL, 'unverified', 1, 0),
  ('dometic-dm2672', NULL, 'Dometic', 'Americana II DM2672', 'Dometic Americana II DM2672 (6 cu ft, 2-way)', '2-way (AC/gas) absorption refrigerator, 6 cubic feet.', 'rv-refrigeration', 'individual', 1455.00, 'street price range $1360-$1550, midpoint shown, cited by Matt 2026-09-12', NULL, 'unverified', 1, 0),
  ('dometic-crx80u', NULL, 'Dometic', 'CRX 80U', 'Dometic CRX 80U Fridge/Freezer', '12V compressor fridge/freezer.', 'rv-refrigeration', 'individual', 1266.99, 'street price citing upfitterswholesale.com, cited by Matt 2026-09-12', NULL, 'unverified', 1, 0),
  ('dometic-crx1080s', NULL, 'Dometic', 'CRX 1080S', 'Dometic CRX 1080S Stainless Steel (2.6 cu ft)', 'Stainless steel 12V compressor fridge/freezer.', 'rv-refrigeration', 'individual', 1990.90, 'street price citing rvfridgeguys.com, cited by Matt 2026-09-12', NULL, 'unverified', 1, 0),
  ('dometic-nrx130e', NULL, 'Dometic', 'NRX 130E', 'Dometic NRX 130E Compressor Refrigerator', '12V compressor refrigerator.', 'rv-refrigeration', 'individual', 1292.99, 'street price citing defender.com, cited by Matt 2026-09-12', NULL, 'unverified', 1, 0),
  ('dometic-coolmatic-cd30', NULL, 'Dometic', 'CoolMatic CD 30', 'Dometic CoolMatic CD 30 Drawer Refrigerator', '12V drawer-style compressor refrigerator.', 'rv-refrigeration', 'individual', 689.99, 'street price citing upfitterswholesale.com, cited by Matt 2026-09-12', NULL, 'unverified', 0, 0),
  ('dometic-cfx5-25', NULL, 'Dometic', 'CFX5 25', 'Dometic CFX5 25 Electric Cooler (25L)', 'Portable 12V electric cooler, 25 liter.', 'rv-refrigeration', 'individual', 899.99, 'dometic.com public price, cited by Matt 2026-09-12', NULL, 'unverified', 0, 0),
  ('dometic-cfx5-55im', NULL, 'Dometic', 'CFX5 55IM', 'Dometic CFX5 55IM Electric Cooler (with Ice Maker)', 'Portable 12V electric cooler with built-in ice maker.', 'rv-refrigeration', 'individual', 1199.99, 'dometic.com public price, cited by Matt 2026-09-12', NULL, 'unverified', 0, 0);
