// Generated by scripts/gen-guide-urls.mjs -- do not edit by hand.
export const GUIDE_URLS = [
  {
    "path": "/guide/",
    "lastmod": "2026-09-14"
  },
  {
    "path": "/guide/12v-vs-120v-appliances-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/30-amp-vs-50-amp-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/awning-fabric-replacement-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/awning-motor-troubleshooting-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/backup-camera-tpms-install-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/battery-charging-voltage-chart/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/best-inverters-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/best-leveling-systems-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/best-rv-tires-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/best-solar-panels-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/bms-explained-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/brake-controller-wiring-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/canbus-multiplex-systems-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/chassis-engine-maintenance-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/coleman-mach-ac-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/converter-inverter-charger-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/dinghy-towing-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/dometic-appliance-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/driving-the-up-winter-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/dump-station-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/electrical-troubleshooting/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/fault-code-index-dometic-onan/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/fifth-wheel-hitch-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/fresh-water-pump-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/gear-we-recommend/",
    "lastmod": "2026-09-14"
  },
  {
    "path": "/guide/generator-manufacturer-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/generator-troubleshooting/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/gvwr-gcwr-payload-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/holding-tank-sanitation-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/inverter-sizing-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/lithium-agm-lead-acid-comparison/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/lp-gas-pressure-specs/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/lp-gas-troubleshooting/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/mppt-vs-pwm-charge-controller-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/norcold-refrigerator-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/off-grid-power-budget-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/peplink-multi-wan-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/plumbing-troubleshooting/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/ppi-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/propane-co-safety-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/roadside-kit-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/roof-coating-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/roof-material-comparison-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/roof-troubleshooting/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/roof-vent-fan-install-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/rv-fire-safety-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/rv-furnace-troubleshooting-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/rv-microwave-troubleshooting-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/rv-storage-prep-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/seasonal-maintenance-checklist/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/slide-out-leveling-troubleshooting-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/slide-out-seal-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/solar-battery-troubleshooting/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/solar-sizing-installation-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/spring-dewinterization-checklist/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/starlink-rv-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/surge-protector-ems-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/tank-sanitizing-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/tank-sensor-troubleshooting-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/tire-aging-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/tire-pressure-load-chart/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/tires-brakes-tpms-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/toilet-systems-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/torque-spec-chart/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/truma-combi-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/underbelly-insulation-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/van-build-electrical-troubleshooting/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/victron-fault-code-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/water-filtration-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/water-heater-troubleshooting-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/weboost-install-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/weighing-your-rig-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/weight-distribution-hitch-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/window-seal-replacement-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/winterization-guide/",
    "lastmod": "2026-09-13"
  },
  {
    "path": "/guide/wire-ampacity-voltage-drop-chart/",
    "lastmod": "2026-09-13"
  }
];
